name: Playwright E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        browser: ['chromium'] # Specify only Chromium (which Playwright uses for Chrome)

    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.browser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-playwright pytest-html

      - name: Install Playwright Browsers (${{ matrix.browser }})
        run: |
          playwright install ${{ matrix.browser }}

      - name: Run Playwright Tests
        run: |
          pytest --browser_name=chrome # Forcefully set browser_name to chrome

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.python-version }}-${{ matrix.browser }}
          path: report/test_report.html
          if-no-files-behavior: ignore